config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get '/legal', to: 'pages#legal', as: 'legal'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [:home, :legal]

  def home
  end

  def legal
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>pivO'tes, Claudine Pradal</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=0"/>
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <link rel="icon" type="image/svg" href="images/favicon.svg" />

    <link href="https://fonts.googleapis.com/css?family=Roboto:300,400" rel="stylesheet">

    <!-- pour google -->
    <meta name="description" content="Curieuse, pétillante, j'aime relever de nouveaux défis chaque jour en collaboration avec mes différents interlocuteurs. Concevoir, Améliorer de nouvelles solutions numérique est un travail d'équipe, un accompagnement, un défi grisant pour assurer une réponse optimale à un besoin. pivO'tes permet aujourd'hui d'aider des clients de tout horizon dans leur aventure digitale." >

    <!-- pour fb -->
    <meta property=“og:title” content="pivO'tes">
    <meta property=“og:image” content="images/logo.png">
    <meta property=“og:description” content="Curieuse, pétillante, j'aime relever de nouveaux défis chaque jour en collaboration avec mes différents interlocuteurs. Concevoir, Améliorer de nouvelles solutions numérique est un travail d'équipe, un accompagnement, un défi grisant pour assurer une réponse optimale à un besoin. pivO'tes permet aujourd'hui d'aider des clients de tout horizon dans leur aventure digitale.">

    <%= csrf_meta_tags %>
    <%= action_cable_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%#= stylesheet_pack_tag 'application', media: 'all' %> <!-- Uncomment if you import CSS in app/javascript/packs/application.js -->
    <!-- Global site tag (gtag.js) - Google Analytics -->
    <script async src="https://www.googletagmanager.com/gtag/js?id=UA-122525070-1"></script>
    <script type="application/ld+json">
    {
      "@context": "http://schema.org",
      "@type": "Organization",
      "url": "https://pivotes.herokuapp.com/",
      "contactPoint": [
        { "@type": "ContactPoint",
          "url": "https://pivotes.herokuapp.com/#contact",
          "email": "clo.pradal@gmail.com",
          "contactType": "customer service"
        }
      ],
      "image": "images/logo.png",
      "description": "Curieuse, pétillante, j'aime relever de nouveaux défis chaque jour en collaboration avec mes différents interlocuteurs. Concevoir, Améliorer de nouvelles solutions numérique est un travail d'équipe, un accompagnement, un défi grisant pour assurer une réponse optimale à un besoin. pivO'tes permet aujourd'hui d'aider des clients de tout horizon dans leur aventure digitale."
    }
    </script>
    <script>
      window.dataLayer = window.dataLayer || [];
      function gtag(){dataLayer.push(arguments);}
      gtag('js', new Date());

      gtag('config', 'UA-122525070-1');
    </script>

  </head>
  <body>
    <%#= render 'shared/navbar' %>
    <%#= render 'shared/flashes' %>
    <%= yield %>
    <%= javascript_include_tag 'application' %>
    <%= javascript_pack_tag 'application' %>
  </body>
</html>

app/views/pages/home.html.erb
<div class="wrapper">
  <div class="banner-menu hidden-xs">
    <a href="#index" id='index-button' class="menu-button active">Accueil</a>
    <a href="#services" id='services-button' class="menu-button">Services</a>
    <a href="#portfolio" id="portfolio-button" class="menu-button">Portfolio</a>
    <a href="#contact" id="contact-button" class="menu-button">Contact</a>
  </div>
   <div class="banner-menu dropdown hidden-sm hidden-md hidden-lg">
      <i class="fa fa-bars dropdown-toggle" data-toggle="dropdown"></i>
      <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
        <li><%= link_to "Accueil", "#index" %></li>
        <li><%= link_to "Services", "#services" %></li>
        <li><%= link_to "Portfolio", "#portfolio" %></li>
        <li><%= link_to "Contact", "#contact" %></li>
      </ul>
    </div>

  <div id="index" class="banner parallax" style="background: url('<%= image_path "fond_pivotes.jpg" %>') no-repeat;">
    <div class="opacity-light bg-dark-gray"></div>
    <div class="banner-content">
      <h1><%= image_tag "logo.png", height: 200 %></h1>
      <h1 class="hidden">pivO'tes, Developpement Web</h1>
      <p>Notre Aventure Numérique</p>
    </div>
  </div>

  <div id="services" class="banner parallax" style="background-image: url('<%= image_path "celebrate.jpg" %>');">
    <div class="opacity-extra-light bg-dark-gray"></div>

    <!-- Vue Normal -->
    <div class="banner-content-around hidden-xs hidden-sm ">
      <!-- <h1><%#= image_tag "service.png", height: 200 %></h1>
      <h1 class="hidden">pivO'tes, Developpement Web</h1> -->
      <div class="logo-card">
        <%= image_tag "logoxxs.svg"%>
        <div>
          <p id="p-title">Services proposés</p>
          <p>Expertise, Technologie, Prestations</p>
        </div>
      </div>

      <div class="flex-column card-space card-position">
        <div class="service-card presta-card">
          <p id="p-title">Prestations</p>
          <p><i class="fas fa-chevron-circle-right"></i> Développement de <strong>Site et d'Application Web</strong></p>
          <p><i class="fas fa-chevron-circle-right"></i> Création et <strong>Gestion de Projets</strong> Web</p>
          <p><i class="fas fa-chevron-circle-right"></i> Parcours d'appropriation du Site avec Fourniture de Notices</p>
          <p><i class="fas fa-chevron-circle-right"></i> <strong>Accompagnement</strong> et Transfert de Connaissance</p>
        </div>
        <div class="service-card techno-card">
          <p id="p-title">Technologies</p>
          <div class="flex-item">
            <div class="flex-column">
              <p><%= image_tag "logo-ruby.png"%></p>
              <p>Ruby</p>
            </div>
            <div class="flex-column">
              <p><%= image_tag "logo-rails.png"%></p>
              <p>Rails</p>
            </div>
          </div>
          <div class="flex-item">
            <div class="flex-column">
              <p><%= image_tag "logo-html.png"%></p>
              <p>HTML</p>
            </div>
            <div class="flex-column">
              <p><%= image_tag "logo-css3.png"%></p>
              <p>CSS</p>
            </div>
          </div>
          <div class="flex-item">
            <div class="flex-column">
              <p><%= image_tag "logo-js.png"%></p>
              <p>Java Script</p>
            </div>
            <div class="flex-column">
              <p><%= image_tag "logo-pg.png"%></p>
              <p>Postgresql</p>
            </div>
          </div>
          <div class="flex-item">
            <div class="flex-column">
              <p><%= image_tag "logo-github.png"%></p>
              <p>Github</p>
            </div>
            <div class="flex-column">
              <p><%= image_tag "logo-heroku.jpg"%></p>
              <p>Heroku</p>
            </div>
          </div>
        </div>
        <div class="service-card expertise-card">
          <p id="p-title">Expertise</p>
          <p>Gestion de projets</p>
          <p>Compétences métiers: <br>Logistique, Achats, Finance,...</p>
          <p>Anglais courant</p>
        </div>
      </div>

    </div>

    <!-- Vue Xs & SM -->
    <div class="banner-content hidden-md hidden-lg">
      <div class="logo-card">
        <%= image_tag "logoxxs.svg"%>
        <div>
          <p id="p-title">Services proposés</p>
          <p>Expertise, Technologie, Prestations</p>
        </div>
      </div>
      <div class="flex-item">
        <div class="service-card service-card-xs">
          <p id="p-title">Prestations</p>
          <p><i class="fas fa-chevron-circle-right"></i> Développement de <strong>Site et d'Application Web</strong></p>
          <p><i class="fas fa-chevron-circle-right"></i> Création et <strong>Gestion de Projets</strong> Web</p>
          <p><i class="fas fa-chevron-circle-right"></i> Parcours d'appropriation du Site avec Fourniture de Notices</p>
          <p><i class="fas fa-chevron-circle-right"></i> <strong>Accompagnement</strong> et Transfert de connaissance</p>
          <p><i class="fas fa-chevron-circle-right"></i> Devis et Premier Rendez vous Gratuit sous une semaine</p>
           <p><i class="fas fa-chevron-circle-right"></i> <strong>Expertise</strong> - Compétences métiers logistique, achat, finance, gestion de projets,...</p>
        </div>
        <div class="service-card service-card-xs">
          <p id="p-title">Technologies</p>
          <div class="flex-item">
            <div class="flex-column">
              <p><%= image_tag "logo-ruby.png"%></p>
              <p>Ruby</p>
            </div>
            <div class="flex-column">
              <p><%= image_tag "logo-rails.png"%></p>
              <p>Rails</p>
            </div>
          </div>
          <div class="flex-item">
            <div class="flex-column">
              <p><%= image_tag "logo-html.png"%></p>
              <p>HTML</p>
            </div>
            <div class="flex-column">
              <p><%= image_tag "logo-css3.png"%></p>
              <p>CSS</p>
            </div>
          </div>
          <div class="flex-item">
            <div class="flex-column">
              <p><%= image_tag "logo-js.png"%></p>
              <p>Java Script</p>
            </div>
            <div class="flex-column">
              <p><%= image_tag "logo-pg.png"%></p>
              <p>Postgresql</p>
            </div>
          </div>
          <div class="flex-item">
            <div class="flex-column">
              <p><%= image_tag "logo-github.png"%></p>
              <p>Github</p>
            </div>
            <div class="flex-column">
              <p><%= image_tag "logo-heroku.jpg"%></p>
              <p>Heroku</p>
            </div>
          </div>
        </div>
        <!-- <div class="service-card service-card-xs">
          <p id="p-title">Expertise</p>
          <p>Gestion de projets</p>
          <p>Compétences métiers : Logistique, Achats, Finance,...</p>
          <p></p>
        </div> -->
      </div>
    </div>

  </div>

  <div id="portfolio" class="banner parallax" style="background-image: linear-gradient(-225deg, rgba(0,101,168,0.6) 0%, rgba(0,36,61,0.6) 50%), url('<%= image_path "fond2.jpg" %>');">
    <div class="opacity-extra-light bg-dark-gray"></div>

    <!-- Vue Normal -->
    <div class="banner-content-around hidden">
      <div class="flex-column card-space">
        <div class="card-img">
        <%= link_to "http://www.riadzouhra.com/", target: "_blank" do %>
          <div class="card">
            <%= image_tag "riad.png"%>
          </div>
        <% end %>
        </div>
        <div class="card-img">
        <%= link_to "http://www.happyseat.fr/", target: "_blank" do %>
          <div class="card">
            <%= image_tag "happy.png"%>
          </div>
        <% end %>
        </div>
      </div>

      <div class="flex-column">
        <div class="logo-card">
          <%= image_tag "logoxxs.svg"%>
          <div>
            <p id="p-title">Projets</p>
            <p>Innover, Collaborer, Accompagner</p>
          </div>
        </div>
        <p id="subtitle">Site et Application web</p>
      </div>
    </div>

   <!--  Vue Xs & SM -->
    <div class="banner-content">
      <div class="logo-card">
        <%= image_tag "logoxxs.svg"%>
        <div>
          <p id="p-title">Projets</p>
          <p>Innover, Collaborer, Accompagner</p>
        </div>
      </div>
      <p id="subtitle">Site et Application web</p>
      <div class="row">
        <div class="flex-center">
          <div class="col-xs-5 col-sm-4 col-md-3">
          <%= link_to "http://www.riadzouhra.com/", target: "_blank" do %>
            <div class="card">
              <%= image_tag "riad.png"%>
            </div>
          <% end %>
          </div>
          <div class="col-xs-5 col-sm-4 col-md-3">
          <%= link_to "http://www.happyseat.fr/", target: "_blank" do %>
            <div class="card">
              <%= image_tag "happy.png"%>
            </div>
          <% end %>
          </div>
        </div>
      </div>
    </div>

  </div>

  <div id="contact" class="banner parallax" style="background: url('<%= image_path "agree.jpg" %>');">
    <div class="opacity-light bg-dark-gray"></div>
    <div class="banner-content">
      <!-- <h1><%#= image_tag "clo.png", height: 200 %></h1> -->
      <div class="logo-card">
        <%= image_tag "logoxxs.svg"%>
        <div>
          <p id="p-title">Claudine Pradal</p>
          <p><a href="mailto:clo.pradal@gmail.com">clo.pradal@gmail.com</a></p>
          <p>www.pivotes.fr</p>
          <p>07 67 51 06 48</p>
        </div>
      </div>

      <h1 class="hidden">pivO'tes, Claudine Pradal, www.pivotes.fr</h1>
      <p id="subtitle">Une Aventure Humaine</p>
    </div>
  </div>

  <div class="mention">
    <p>Site internet réalisé par pivO'tes - <%= link_to "Mentions légales", legal_path %></p>
  </div>
</div>

app/views/pages/legal.html.erb
<%= render 'shared/navbar' %>

<div class="banner-small" style="background: url('<%= image_path "fond_pivotes.jpg" %>') no-repeat;">
  <div class="banner-content">
    <h1>Mentions légales</h1>
  </div>
</div>

<div class="container font-legal wrapper-legal">
  <h3>1. Présentation du site.</h3>
  <p>En vertu de l'article 6 de la loi n° 2004-575 du 21 juin 2004 pour la confiance dans l'économie numérique, il est précisé aux utilisateurs du site <a href="http://www.pivotes.fr/">www.pivotes.fr</a> l'identité des différents intervenants dans le cadre de sa réalisation et de son suivi :</p>
  <p><strong>Propriétaire</strong> : Le site  appartient à la marque pivO'tes hébergé juridiquement par la SCOP Coop'Alpha, Scop ARL à capital variable - RCS Bordeaux 482 371 481 - Siret 48237148100052 - APE 7022Z - N° TVA FR70482371481- OF N° 72330705833
  Sa représentante légale et directrice de publication est Karine LABAT PAPIN, gérante.  – 3 Rue Cantelaudette 33310 Lormont <br />
  <strong>Créateur</strong>  : Claudine Pradal<br />
  <strong>Responsable publication</strong> : Claudine Pradal – clo.pradal@gmail.com<br />
  Le responsable publication est une personne physique ou une personne morale.<br />
  <strong>Webmaster</strong> : Claudine Pradal<br />
  <strong>Hébergeur</strong> : Heroku Inc., 650 7th Street, San Francisco, CA (tel : +33 1 (877) 563-4311)<br />
 <br />
  Le modèle de mentions légales est offert par Subdelirium.com <a target="_blank" href="https://www.subdelirium.com/generateur-de-mentions-legales/" alt="Modèle de mentions légales">Modèle de mentions légales</a></p>

  <h3>2. Conditions générales d’utilisation du site et des services proposés.</h3>
  <p>L’utilisation du site <a href="/">www.pivotes.fr</a> implique l’acceptation pleine et entière des conditions générales d’utilisation ci-après décrites. Ces conditions d’utilisation sont susceptibles d’être modifiées ou complétées à tout moment, les utilisateurs du site <a href="/">www.pivotes.fr</a> sont donc invités à les consulter de manière régulière.</p>
  <p>Ce site est normalement accessible à tout moment aux utilisateurs. Une interruption pour raison de maintenance technique peut être toutefois décidée par Claudine Pradal, qui s’efforcera alors de communiquer préalablement aux utilisateurs les dates et heures de l’intervention.</p>
  <p>Le site <a href="/">www.pivotes.fr</a> est mis à jour régulièrement par Claudine Pradal. De la même façon, les mentions légales peuvent être modifiées à tout moment : elles s’imposent néanmoins à l’utilisateur qui est invité à s’y référer le plus souvent possible afin d’en prendre connaissance.</p>
  <h3>3. Description des services fournis.</h3>
  <p>Le site <a href="/">www.pivotes.fr</a> a pour objet de fournir une information concernant l’ensemble des activités de la société.</p>
  <p>Claudine Pradal s’efforce de fournir sur le site <a href="/">www.pivotes.fr</a> des informations aussi précises que possible. Toutefois, il ne pourra être tenue responsable des omissions, des inexactitudes et des carences dans la mise à jour, qu’elles soient de son fait ou du fait des tiers partenaires qui lui fournissent ces informations.</p>
  <p>Tous les informations indiquées sur le site <a href="/">www.pivotes.fr</a> sont données à titre indicatif, et sont susceptibles d’évoluer. Par ailleurs, les renseignements figurant sur le site <a href="/">www.pivotes.fr</a> ne sont pas exhaustifs. Ils sont donnés sous réserve de modifications ayant été apportées depuis leur mise en ligne.</p>
  <h3>4. Limitations contractuelles sur les données techniques.</h3>
  <p>Le site utilise la technologie JavaScript.</p>
  <p>Le site Internet ne pourra être tenu responsable de dommages matériels liés à l’utilisation du site. De plus, l’utilisateur du site s’engage à accéder au site en utilisant un matériel récent, ne contenant pas de virus et avec un navigateur de dernière génération mis-à-jour</p>
  <h3>5. Propriété intellectuelle et contrefaçons.</h3>
  <p>Claudine Pradal est propriétaire des droits de propriété intellectuelle ou détient les droits d’usage sur tous les éléments accessibles sur le site, notamment les textes, images, graphismes, logo, icônes, sons, logiciels.</p>
  <p>Toute reproduction, représentation, modification, publication, adaptation de tout ou partie des éléments du site, quel que soit le moyen ou le procédé utilisé, est interdite, sauf autorisation écrite préalable de : Claudine Pradal.</p>
  <p>Toute exploitation non autorisée du site ou de l’un quelconque des éléments qu’il contient sera considérée comme constitutive d’une contrefaçon et poursuivie conformément aux dispositions des articles L.335-2 et suivants du Code de Propriété Intellectuelle.</p>
  <h3>6. Limitations de responsabilité.</h3>
  <p>Claudine Pradal ne pourra être tenue responsable des dommages directs et indirects causés au matériel de l’utilisateur, lors de l’accès au site www.pivotes.fr, et résultant soit de l’utilisation d’un matériel ne répondant pas aux spécifications indiquées au point 4, soit de l’apparition d’un bug ou d’une incompatibilité.</p>
  <p>Claudine Pradal ne pourra également être tenue responsable des dommages indirects (tels par exemple qu’une perte de marché ou perte d’une chance) consécutifs à l’utilisation du site <a href="/">www.pivotes.fr</a>.</p>
  <p>Des espaces interactifs (possibilité de poser des questions dans l’espace contact) sont à la disposition des utilisateurs. Claudine Pradal se réserve le droit de supprimer, sans mise en demeure préalable, tout contenu déposé dans cet espace qui contreviendrait à la législation applicable en France, en particulier aux dispositions relatives à la protection des données. Le cas échéant, Claudine Pradal se réserve également la possibilité de mettre en cause la responsabilité civile et/ou pénale de l’utilisateur, notamment en cas de message à caractère raciste, injurieux, diffamant, ou pornographique, quel que soit le support utilisé (texte, photographie…).</p>
  <h3>7. Gestion des données personnelles.</h3>
  <p>En France, les données personnelles sont notamment protégées par la loi n° 78-87 du 6 janvier 1978, la loi n° 2004-801 du 6 août 2004, l'article L. 226-13 du Code pénal et la Directive Européenne du 24 octobre 1995.</p>
  <p>A l'occasion de l'utilisation du site <a href="/">www.pivotes.fr</a>, peuvent êtres recueillies : l'URL des liens par l'intermédiaire desquels l'utilisateur a accédé au site <a href="/">www.pivotes.fr</a>, le fournisseur d'accès de l'utilisateur, l'adresse de protocole Internet (IP) de l'utilisateur.</p>
  <p> En tout état de cause Claudine Pradal ne collecte des informations personnelles relatives à l'utilisateur que pour le besoin de certains services proposés par le site <a href="/">www.pivotes.fr</a>. L'utilisateur fournit ces informations en toute connaissance de cause, notamment lorsqu'il procède par lui-même à leur saisie. Il est alors précisé à l'utilisateur du site <a href="/">www.pivotes.fr</a> l’obligation ou non de fournir ces informations.</p>
  <p>Conformément aux dispositions des articles 38 et suivants de la loi 78-17 du 6 janvier 1978 relative à l’informatique, aux fichiers et aux libertés, tout utilisateur dispose d’un droit d’accès, de rectification et d’opposition aux données personnelles le concernant, en effectuant sa demande écrite et signée, accompagnée d’une copie du titre d’identité avec signature du titulaire de la pièce, en précisant l’adresse à laquelle la réponse doit être envoyée.</p>
  <p>Aucune information personnelle de l'utilisateur du site <a href="/">www.pivotes.fr</a> n'est publiée à l'insu de l'utilisateur, échangée, transférée, cédée ou vendue sur un support quelconque à des tiers. Seule l'hypothèse du rachat de Claudine Pradal et de ses droits permettrait la transmission des dites informations à l'éventuel acquéreur qui serait à son tour tenu de la même obligation de conservation et de modification des données vis à vis de l'utilisateur du site <a href="/">www.pivotes.fr</a>.</p>
  <p>Le site n'est pas déclaré à la CNIL car il ne recueille pas d'informations personnelles. .</p>
  <p>Les bases de données sont protégées par les dispositions de la loi du 1er juillet 1998 transposant la directive 96/9 du 11 mars 1996 relative à la protection juridique des bases de données.</p>
  <h3>8. Liens hypertextes et cookies.</h3>
  <p>Le site <a href="/">www.pivotes.fr</a> contient un certain nombre de liens hypertextes vers d’autres sites, mis en place avec l’autorisation de Claudine Pradal. Cependant, Claudine Pradal n’a pas la possibilité de vérifier le contenu des sites ainsi visités, et n’assumera en conséquence aucune responsabilité de ce fait.</p>
  <p>La navigation sur le site <a href="/">www.pivotes.fr</a> est susceptible de provoquer l’installation de cookie(s) sur l’ordinateur de l’utilisateur. Un cookie est un fichier de petite taille, qui ne permet pas l’identification de l’utilisateur, mais qui enregistre des informations relatives à la navigation d’un ordinateur sur un site. Les données ainsi obtenues visent à faciliter la navigation ultérieure sur le site, et ont également vocation à permettre diverses mesures de fréquentation.</p>
  <p>Le refus d’installation d’un cookie peut entraîner l’impossibilité d’accéder à certains services. L’utilisateur peut toutefois configurer son ordinateur de la manière suivante, pour refuser l’installation des cookies :</p>
  <p>Sous Internet Explorer : onglet outil (pictogramme en forme de rouage en haut a droite) / options internet. Cliquez sur Confidentialité et choisissez Bloquer tous les cookies. Validez sur Ok.</p>
  <p>Sous Firefox : en haut de la fenêtre du navigateur, cliquez sur le bouton Firefox, puis aller dans l'onglet Options. Cliquer sur l'onglet Vie privée.
    Paramétrez les Règles de conservation sur :  utiliser les paramètres personnalisés pour l'historique. Enfin décochez-la pour  désactiver les cookies.</p>
  <p>Sous Safari : Cliquez en haut à droite du navigateur sur le pictogramme de menu (symbolisé par un rouage). Sélectionnez Paramètres. Cliquez sur Afficher les paramètres avancés. Dans la section "Confidentialité", cliquez sur Paramètres de contenu. Dans la section "Cookies", vous pouvez bloquer les cookies.</p>
  <p>Sous Chrome : Cliquez en haut à droite du navigateur sur le pictogramme de menu (symbolisé par trois lignes horizontales). Sélectionnez Paramètres. Cliquez sur Afficher les paramètres avancés. Dans la section "Confidentialité", cliquez sur préférences.  Dans l'onglet "Confidentialité", vous pouvez bloquer les cookies.</p>

  <h3>9. Droit applicable et attribution de juridiction.</h3>
  <p>Tout litige en relation avec l’utilisation du site <a href="/">www.pivotes.fr</a> est soumis au droit français. Il est fait attribution exclusive de juridiction aux tribunaux compétents de Paris.</p>
  <h3>10. Les principales lois concernées.</h3>
  <p>Loi n° 78-17 du 6 janvier 1978, notamment modifiée par la loi n° 2004-801 du 6 août 2004 relative à l'informatique, aux fichiers et aux libertés.</p>
  <p> Loi n° 2004-575 du 21 juin 2004 pour la confiance dans l'économie numérique.</p>
  <h3>11. Lexique.</h3>
  <p>Utilisateur : Internaute se connectant, utilisant le site susnommé.</p>
  <p>Informations personnelles : « les informations qui permettent, sous quelque forme que ce soit, directement ou non, l'identification des personnes physiques auxquelles elles s'appliquent » (article 4 de la loi n° 78-17 du 6 janvier 1978).</p>


</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar-wagon">
  <!-- Logo -->
  <%= link_to root_path, class: "navbar-wagon-brand" do %>
    <%= image_tag "logo.png", height: 50 %>
  <% end %>

  <!-- Right Navigation -->
  <div class="navbar-wagon-right hidden-xs hidden-sm">
      <!-- Links when logged in -->
      <%#= link_to "Accueil", root_path, class: "navbar-wagon-item navbar-wagon-link" %>
      <%#= link_to "Projets", "#", class: "navbar-wagon-item navbar-wagon-link" %>
      <%#= link_to "Technologie", "#", class: "navbar-wagon-item navbar-wagon-link" %>
      <%#= link_to "Contact", "#", class: "navbar-wagon-item navbar-wagon-link" %>
  </div>

  <!-- Dropdown list appearing on mobile only -->
  <div class="navbar-wagon-item">
    <div class="dropdown">
      <i class="fa fa-bars dropdown-toggle" data-toggle="dropdown"></i>
      <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
        <li><%= link_to "Accueil", root_path %></li>
        <li><%= link_to "Services", "/#services" %></li>
        <li><%= link_to "Portfolio", "/#portfolio" %></li>
        <li><%= link_to "Contact", "/#contact" %></li>
 <!--    <li><a href="#">Some mobile link</a></li>
        <li><a href="#">Other one</a></li>
        <li><a href="#">Other one</a></li> -->
      </ul>
    </div>
  </div>
</div>